version: "2"
services: 
  server:
    container_name: crypto-server
    restart: always
    build: ./
    ports:
      - "8080:8080"
    links:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
  mongo:
    container_name: crypto-server-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"