version: "2"
services: 
  server:
    container_name: crypto-server
    restart: always
    build: ./
    ports:
      - "80:8080"
    links:
      - mongo
  mongo:
    container_name: crypto-server-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"